name: Release Build of White Box CLI
run-name: ${{ github.actor }} is running a release build
on: [push]
jobs:
  Release-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make
