name: Release Build of White Box CLI
run-name: ${{ github.actor }} is running a release build
on: [push]
jobs:
  Release-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cd cli && make
      - run: cd daemon && make
      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Create tar.gz file
        uses: a7ul/tar-action@v1.1.3
        with:
          command: c
          files: |
            cli/wb
            daemon/wbd
          outPath: wb-linux-${{ steps.getversion.outputs.version }}.tar.gz
      - name: Authenticate with GCP
        uses: google-github-actions/setup-gcloud@v1.1.0
        with:
          service_account: 'github-service-account@vpnwebsite-972ea.iam.gserviceaccount.com'
          workload_identity_provider: projects/61621990789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
      - name: Upload to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1.0.2
        with:
          path: wb-linux-${{ steps.getversion.outputs.version }}.tar.gz
          destination: wbvpn-release/wb-linux-${{ steps.getversion.outputs.version }}.tar.gz
      - name: Upload to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1.0.2
        with:
          path: wb-linux-${{ steps.getversion.outputs.version }}.tar.gz
          destination: wbvpn-release/wb-linux-latest.tar.gz
